# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: en
title: Jekyll-IndieWeb
email: shaun.m.bruce@gmail.com
description: A Jekyll quick start to getting up and going with the indieweb.
# Webmentions - leave blank (remove "yes") if you would not like to receive & display webmentions from other sites
webmentions:

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.shaunbruce.com" # the base hostname & protocol for your site
twitter_username: sbruce
github_username:  sbruce
instagram_username:
flickr_username:
foursquare_username:
# Tumblr URL
tumblr_url:
# Linkedin profile URL - Expecting a full url, not username
linkedin_url:
# Facebook profile URL - Expecting a full url, not username
facebook_url:


# Can be over ridden with author: in Front Matter
author: Shaun Bruce

# Expecting a full url, not relative to site.url
author_img: https://avatars3.githubusercontent.com/u/3083652

# Build settings
markdown: kramdown
gems:
  - github-pages
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist

paginate: 5
